package org.example;

public class AddRanks {

    //Populates cultivation ranks with ordered progression
    public static void AddCultivationRanks() {
        Main.CultivationRanks.add("Mortal");
        Main.CultivationRanks.add("Qi Gathering Early G0");
        Main.CultivationRanks.add("Qi Gathering Early G1");
        Main.CultivationRanks.add("Qi Gathering Early G2");
        Main.CultivationRanks.add("Qi Gathering Early G3");
        Main.CultivationRanks.add("Qi Gathering Early G4");
        Main.CultivationRanks.add("Qi Gathering Early G5");
        Main.CultivationRanks.add("Qi Gathering Early G6");
        Main.CultivationRanks.add("Qi Gathering Early G7");
        Main.CultivationRanks.add("Qi Gathering Early G8");
        Main.CultivationRanks.add("Qi Gathering Early G9");
        Main.CultivationRanks.add("Qi Gathering Middle G0");
        Main.CultivationRanks.add("Qi Gathering Middle G1");
        Main.CultivationRanks.add("Qi Gathering Middle G2");
        Main.CultivationRanks.add("Qi Gathering Middle G3");
        Main.CultivationRanks.add("Qi Gathering Middle G4");
        Main.CultivationRanks.add("Qi Gathering Middle G5");
        Main.CultivationRanks.add("Qi Gathering Middle G6");
        Main.CultivationRanks.add("Qi Gathering Middle G7");
        Main.CultivationRanks.add("Qi Gathering Middle G8");
        Main.CultivationRanks.add("Qi Gathering Middle G9");
        Main.CultivationRanks.add("Qi Gathering Late G0");
        Main.CultivationRanks.add("Qi Gathering Late G1");
        Main.CultivationRanks.add("Qi Gathering Late G2");
        Main.CultivationRanks.add("Qi Gathering Late G3");
        Main.CultivationRanks.add("Qi Gathering Late G4");
        Main.CultivationRanks.add("Qi Gathering Late G5");
        Main.CultivationRanks.add("Qi Gathering Late G6");
        Main.CultivationRanks.add("Qi Gathering Late G7");
        Main.CultivationRanks.add("Qi Gathering Late G8");
        Main.CultivationRanks.add("Qi Gathering Late G9");
        Main.CultivationRanks.add("Qi Gathering Peak G0");
        Main.CultivationRanks.add("Qi Gathering Peak G1");
        Main.CultivationRanks.add("Qi Gathering Peak G2");
        Main.CultivationRanks.add("Qi Gathering Peak G3");
        Main.CultivationRanks.add("Qi Gathering Peak G4");
        Main.CultivationRanks.add("Qi Gathering Peak G5");
        Main.CultivationRanks.add("Qi Gathering Peak G6");
        Main.CultivationRanks.add("Qi Gathering Peak G7");
        Main.CultivationRanks.add("Qi Gathering Peak G8");
        Main.CultivationRanks.add("Qi Gathering Peak G9");
        Main.CultivationRanks.add("Foundation Establishment Early G0");
        Main.CultivationRanks.add("Foundation Establishment Early G1");
        Main.CultivationRanks.add("Foundation Establishment Early G2");
        Main.CultivationRanks.add("Foundation Establishment Early G3");
        Main.CultivationRanks.add("Foundation Establishment Early G4");
        Main.CultivationRanks.add("Foundation Establishment Early G5");
        Main.CultivationRanks.add("Foundation Establishment Early G6");
        Main.CultivationRanks.add("Foundation Establishment Early G7");
        Main.CultivationRanks.add("Foundation Establishment Early G8");
        Main.CultivationRanks.add("Foundation Establishment Early G9");
        Main.CultivationRanks.add("Foundation Establishment Middle G0");
        Main.CultivationRanks.add("Foundation Establishment Middle G1");
        Main.CultivationRanks.add("Foundation Establishment Middle G2");
        Main.CultivationRanks.add("Foundation Establishment Middle G3");
        Main.CultivationRanks.add("Foundation Establishment Middle G4");
        Main.CultivationRanks.add("Foundation Establishment Middle G5");
        Main.CultivationRanks.add("Foundation Establishment Middle G6");
        Main.CultivationRanks.add("Foundation Establishment Middle G7");
        Main.CultivationRanks.add("Foundation Establishment Middle G8");
        Main.CultivationRanks.add("Foundation Establishment Middle G9");
        Main.CultivationRanks.add("Foundation Establishment Late G0");
        Main.CultivationRanks.add("Foundation Establishment Late G1");
        Main.CultivationRanks.add("Foundation Establishment Late G2");
        Main.CultivationRanks.add("Foundation Establishment Late G3");
        Main.CultivationRanks.add("Foundation Establishment Late G4");
        Main.CultivationRanks.add("Foundation Establishment Late G5");
        Main.CultivationRanks.add("Foundation Establishment Late G6");
        Main.CultivationRanks.add("Foundation Establishment Late G7");
        Main.CultivationRanks.add("Foundation Establishment Late G8");
        Main.CultivationRanks.add("Foundation Establishment Late G9");
        Main.CultivationRanks.add("Foundation Establishment Peak G0");
        Main.CultivationRanks.add("Foundation Establishment Peak G1");
        Main.CultivationRanks.add("Foundation Establishment Peak G2");
        Main.CultivationRanks.add("Foundation Establishment Peak G3");
        Main.CultivationRanks.add("Foundation Establishment Peak G4");
        Main.CultivationRanks.add("Foundation Establishment Peak G5");
        Main.CultivationRanks.add("Foundation Establishment Peak G6");
        Main.CultivationRanks.add("Foundation Establishment Peak G7");
        Main.CultivationRanks.add("Foundation Establishment Peak G8");
        Main.CultivationRanks.add("Foundation Establishment Peak G9");
        Main.CultivationRanks.add("Core Formation Early G0");
        Main.CultivationRanks.add("Core Formation Early G1");
        Main.CultivationRanks.add("Core Formation Early G2");
        Main.CultivationRanks.add("Core Formation Early G3");
        Main.CultivationRanks.add("Core Formation Early G4");
        Main.CultivationRanks.add("Core Formation Early G5");
        Main.CultivationRanks.add("Core Formation Early G6");
        Main.CultivationRanks.add("Core Formation Early G7");
        Main.CultivationRanks.add("Core Formation Early G8");
        Main.CultivationRanks.add("Core Formation Early G9");
        Main.CultivationRanks.add("Core Formation Middle G0");
        Main.CultivationRanks.add("Core Formation Middle G1");
        Main.CultivationRanks.add("Core Formation Middle G2");
        Main.CultivationRanks.add("Core Formation Middle G3");
        Main.CultivationRanks.add("Core Formation Middle G4");
        Main.CultivationRanks.add("Core Formation Middle G5");
        Main.CultivationRanks.add("Core Formation Middle G6");
        Main.CultivationRanks.add("Core Formation Middle G7");
        Main.CultivationRanks.add("Core Formation Middle G8");
        Main.CultivationRanks.add("Core Formation Middle G9");
        Main.CultivationRanks.add("Core Formation Late G0");
        Main.CultivationRanks.add("Core Formation Late G1");
        Main.CultivationRanks.add("Core Formation Late G2");
        Main.CultivationRanks.add("Core Formation Late G3");
        Main.CultivationRanks.add("Core Formation Late G4");
        Main.CultivationRanks.add("Core Formation Late G5");
        Main.CultivationRanks.add("Core Formation Late G6");
        Main.CultivationRanks.add("Core Formation Late G7");
        Main.CultivationRanks.add("Core Formation Late G8");
        Main.CultivationRanks.add("Core Formation Late G9");
        Main.CultivationRanks.add("Core Formation Peak G0");
        Main.CultivationRanks.add("Core Formation Peak G1");
        Main.CultivationRanks.add("Core Formation Peak G2");
        Main.CultivationRanks.add("Core Formation Peak G3");
        Main.CultivationRanks.add("Core Formation Peak G4");
        Main.CultivationRanks.add("Core Formation Peak G5");
        Main.CultivationRanks.add("Core Formation Peak G6");
        Main.CultivationRanks.add("Core Formation Peak G7");
        Main.CultivationRanks.add("Core Formation Peak G8");
        Main.CultivationRanks.add("Core Formation Peak G9");
        Main.CultivationRanks.add("Nascent Soul Early G0");
        Main.CultivationRanks.add("Nascent Soul Early G1");
        Main.CultivationRanks.add("Nascent Soul Early G2");
        Main.CultivationRanks.add("Nascent Soul Early G3");
        Main.CultivationRanks.add("Nascent Soul Early G4");
        Main.CultivationRanks.add("Nascent Soul Early G5");
        Main.CultivationRanks.add("Nascent Soul Early G6");
        Main.CultivationRanks.add("Nascent Soul Early G7");
        Main.CultivationRanks.add("Nascent Soul Early G8");
        Main.CultivationRanks.add("Nascent Soul Early G9");
        Main.CultivationRanks.add("Nascent Soul Middle G0");
        Main.CultivationRanks.add("Nascent Soul Middle G1");
        Main.CultivationRanks.add("Nascent Soul Middle G2");
        Main.CultivationRanks.add("Nascent Soul Middle G3");
        Main.CultivationRanks.add("Nascent Soul Middle G4");
        Main.CultivationRanks.add("Nascent Soul Middle G5");
        Main.CultivationRanks.add("Nascent Soul Middle G6");
        Main.CultivationRanks.add("Nascent Soul Middle G7");
        Main.CultivationRanks.add("Nascent Soul Middle G8");
        Main.CultivationRanks.add("Nascent Soul Middle G9");
        Main.CultivationRanks.add("Nascent Soul Late G0");
        Main.CultivationRanks.add("Nascent Soul Late G1");
        Main.CultivationRanks.add("Nascent Soul Late G2");
        Main.CultivationRanks.add("Nascent Soul Late G3");
        Main.CultivationRanks.add("Nascent Soul Late G4");
        Main.CultivationRanks.add("Nascent Soul Late G5");
        Main.CultivationRanks.add("Nascent Soul Late G6");
        Main.CultivationRanks.add("Nascent Soul Late G7");
        Main.CultivationRanks.add("Nascent Soul Late G8");
        Main.CultivationRanks.add("Nascent Soul Late G9");
        Main.CultivationRanks.add("Nascent Soul Peak G0");
        Main.CultivationRanks.add("Nascent Soul Peak G1");
        Main.CultivationRanks.add("Nascent Soul Peak G2");
        Main.CultivationRanks.add("Nascent Soul Peak G3");
        Main.CultivationRanks.add("Nascent Soul Peak G4");
        Main.CultivationRanks.add("Nascent Soul Peak G5");
        Main.CultivationRanks.add("Nascent Soul Peak G6");
        Main.CultivationRanks.add("Nascent Soul Peak G7");
        Main.CultivationRanks.add("Nascent Soul Peak G8");
        Main.CultivationRanks.add("Nascent Soul Peak G9");
        Main.CultivationRanks.add("Deity Transformation Early G0");
        Main.CultivationRanks.add("Deity Transformation Early G1");
        Main.CultivationRanks.add("Deity Transformation Early G2");
        Main.CultivationRanks.add("Deity Transformation Early G3");
        Main.CultivationRanks.add("Deity Transformation Early G4");
        Main.CultivationRanks.add("Deity Transformation Early G5");
        Main.CultivationRanks.add("Deity Transformation Early G6");
        Main.CultivationRanks.add("Deity Transformation Early G7");
        Main.CultivationRanks.add("Deity Transformation Early G8");
        Main.CultivationRanks.add("Deity Transformation Early G9");
        Main.CultivationRanks.add("Deity Transformation Middle G0");
        Main.CultivationRanks.add("Deity Transformation Middle G1");
        Main.CultivationRanks.add("Deity Transformation Middle G2");
        Main.CultivationRanks.add("Deity Transformation Middle G3");
        Main.CultivationRanks.add("Deity Transformation Middle G4");
        Main.CultivationRanks.add("Deity Transformation Middle G5");
        Main.CultivationRanks.add("Deity Transformation Middle G6");
        Main.CultivationRanks.add("Deity Transformation Middle G7");
        Main.CultivationRanks.add("Deity Transformation Middle G8");
        Main.CultivationRanks.add("Deity Transformation Middle G9");
        Main.CultivationRanks.add("Deity Transformation Late G0");
        Main.CultivationRanks.add("Deity Transformation Late G1");
        Main.CultivationRanks.add("Deity Transformation Late G2");
        Main.CultivationRanks.add("Deity Transformation Late G3");
        Main.CultivationRanks.add("Deity Transformation Late G4");
        Main.CultivationRanks.add("Deity Transformation Late G5");
        Main.CultivationRanks.add("Deity Transformation Late G6");
        Main.CultivationRanks.add("Deity Transformation Late G7");
        Main.CultivationRanks.add("Deity Transformation Late G8");
        Main.CultivationRanks.add("Deity Transformation Late G9");
        Main.CultivationRanks.add("Deity Transformation Peak G0");
        Main.CultivationRanks.add("Deity Transformation Peak G1");
        Main.CultivationRanks.add("Deity Transformation Peak G2");
        Main.CultivationRanks.add("Deity Transformation Peak G3");
        Main.CultivationRanks.add("Deity Transformation Peak G4");
        Main.CultivationRanks.add("Deity Transformation Peak G5");
        Main.CultivationRanks.add("Deity Transformation Peak G6");
        Main.CultivationRanks.add("Deity Transformation Peak G7");
        Main.CultivationRanks.add("Deity Transformation Peak G8");
        Main.CultivationRanks.add("Deity Transformation Peak G9");
        Main.CultivationRanks.add("Immortality");
    }
    //Populates martial ranks with ordered progression
    public static void AddMartialRanks() {
        Main.MartialRanks.add("Lesser Martial Disciple I");
        Main.MartialRanks.add("Lesser Martial Disciple II");
        Main.MartialRanks.add("Lesser Martial Disciple III");
        Main.MartialRanks.add("Lesser Martial Disciple IV");
        Main.MartialRanks.add("Lesser Martial Disciple V");
        Main.MartialRanks.add("Lesser Martial Disciple VI");
        Main.MartialRanks.add("Lesser Martial Disciple VII");
        Main.MartialRanks.add("Lesser Martial Disciple VIII");
        Main.MartialRanks.add("Lesser Martial Disciple IX");
        Main.MartialRanks.add("Lesser Martial Disciple X");
        Main.MartialRanks.add("Martial Disciple I");
        Main.MartialRanks.add("Martial Disciple II");
        Main.MartialRanks.add("Martial Disciple III");
        Main.MartialRanks.add("Martial Disciple IV");
        Main.MartialRanks.add("Martial Disciple V");
        Main.MartialRanks.add("Martial Disciple VI");
        Main.MartialRanks.add("Martial Disciple VII");
        Main.MartialRanks.add("Martial Disciple VIII");
        Main.MartialRanks.add("Martial Disciple IX");
        Main.MartialRanks.add("Martial Disciple X");
        Main.MartialRanks.add("Greater Martial Disciple I");
        Main.MartialRanks.add("Greater Martial Disciple II");
        Main.MartialRanks.add("Greater Martial Disciple III");
        Main.MartialRanks.add("Greater Martial Disciple IV");
        Main.MartialRanks.add("Greater Martial Disciple V");
        Main.MartialRanks.add("Greater Martial Disciple VI");
        Main.MartialRanks.add("Greater Martial Disciple VII");
        Main.MartialRanks.add("Greater Martial Disciple VIII");
        Main.MartialRanks.add("Greater Martial Disciple IX");
        Main.MartialRanks.add("Greater Martial Disciple X");
        Main.MartialRanks.add("Peak Martial Disciple I");
        Main.MartialRanks.add("Peak Martial Disciple II");
        Main.MartialRanks.add("Peak Martial Disciple III");
        Main.MartialRanks.add("Peak Martial Disciple IV");
        Main.MartialRanks.add("Peak Martial Disciple V");
        Main.MartialRanks.add("Peak Martial Disciple VI");
        Main.MartialRanks.add("Peak Martial Disciple VII");
        Main.MartialRanks.add("Peak Martial Disciple VIII");
        Main.MartialRanks.add("Peak Martial Disciple IX");
        Main.MartialRanks.add("Peak Martial Disciple X");
        Main.MartialRanks.add("Lesser Martial Master I");
        Main.MartialRanks.add("Lesser Martial Master II");
        Main.MartialRanks.add("Lesser Martial Master III");
        Main.MartialRanks.add("Lesser Martial Master IV");
        Main.MartialRanks.add("Lesser Martial Master V");
        Main.MartialRanks.add("Lesser Martial Master VI");
        Main.MartialRanks.add("Lesser Martial Master VII");
        Main.MartialRanks.add("Lesser Martial Master VIII");
        Main.MartialRanks.add("Lesser Martial Master IX");
        Main.MartialRanks.add("Lesser Martial Master X");
        Main.MartialRanks.add("Martial Master I");
        Main.MartialRanks.add("Martial Master II");
        Main.MartialRanks.add("Martial Master III");
        Main.MartialRanks.add("Martial Master IV");
        Main.MartialRanks.add("Martial Master V");
        Main.MartialRanks.add("Martial Master VI");
        Main.MartialRanks.add("Martial Master VII");
        Main.MartialRanks.add("Martial Master VIII");
        Main.MartialRanks.add("Martial Master IX");
        Main.MartialRanks.add("Martial Master X");
        Main.MartialRanks.add("Greater Martial Master I");
        Main.MartialRanks.add("Greater Martial Master II");
        Main.MartialRanks.add("Greater Martial Master III");
        Main.MartialRanks.add("Greater Martial Master IV");
        Main.MartialRanks.add("Greater Martial Master V");
        Main.MartialRanks.add("Greater Martial Master VI");
        Main.MartialRanks.add("Greater Martial Master VII");
        Main.MartialRanks.add("Greater Martial Master VIII");
        Main.MartialRanks.add("Greater Martial Master IX");
        Main.MartialRanks.add("Greater Martial Master X");
        Main.MartialRanks.add("Peak Martial Master I");
        Main.MartialRanks.add("Peak Martial Master II");
        Main.MartialRanks.add("Peak Martial Master III");
        Main.MartialRanks.add("Peak Martial Master IV");
        Main.MartialRanks.add("Peak Martial Master V");
        Main.MartialRanks.add("Peak Martial Master VI");
        Main.MartialRanks.add("Peak Martial Master VII");
        Main.MartialRanks.add("Peak Martial Master VIII");
        Main.MartialRanks.add("Peak Martial Master IX");
        Main.MartialRanks.add("Peak Martial Master X");
        Main.MartialRanks.add("Lesser Martial Grandmaster I");
        Main.MartialRanks.add("Lesser Martial Grandmaster II");
        Main.MartialRanks.add("Lesser Martial Grandmaster III");
        Main.MartialRanks.add("Lesser Martial Grandmaster IV");
        Main.MartialRanks.add("Lesser Martial Grandmaster V");
        Main.MartialRanks.add("Lesser Martial Grandmaster VI");
        Main.MartialRanks.add("Lesser Martial Grandmaster VII");
        Main.MartialRanks.add("Lesser Martial Grandmaster VIII");
        Main.MartialRanks.add("Lesser Martial Grandmaster IX");
        Main.MartialRanks.add("Lesser Martial Grandmaster X");
        Main.MartialRanks.add("Martial Grandmaster I");
        Main.MartialRanks.add("Martial Grandmaster II");
        Main.MartialRanks.add("Martial Grandmaster III");
        Main.MartialRanks.add("Martial Grandmaster IV");
        Main.MartialRanks.add("Martial Grandmaster V");
        Main.MartialRanks.add("Martial Grandmaster VI");
        Main.MartialRanks.add("Martial Grandmaster VII");
        Main.MartialRanks.add("Martial Grandmaster VIII");
        Main.MartialRanks.add("Martial Grandmaster IX");
        Main.MartialRanks.add("Martial Grandmaster X");
        Main.MartialRanks.add("Greater Martial Grandmaster I");
        Main.MartialRanks.add("Greater Martial Grandmaster II");
        Main.MartialRanks.add("Greater Martial Grandmaster III");
        Main.MartialRanks.add("Greater Martial Grandmaster IV");
        Main.MartialRanks.add("Greater Martial Grandmaster V");
        Main.MartialRanks.add("Greater Martial Grandmaster VI");
        Main.MartialRanks.add("Greater Martial Grandmaster VII");
        Main.MartialRanks.add("Greater Martial Grandmaster VIII");
        Main.MartialRanks.add("Greater Martial Grandmaster IX");
        Main.MartialRanks.add("Greater Martial Grandmaster X");
        Main.MartialRanks.add("Peak Martial Grandmaster I");
        Main.MartialRanks.add("Peak Martial Grandmaster II");
        Main.MartialRanks.add("Peak Martial Grandmaster III");
        Main.MartialRanks.add("Peak Martial Grandmaster IV");
        Main.MartialRanks.add("Peak Martial Grandmaster V");
        Main.MartialRanks.add("Peak Martial Grandmaster VI");
        Main.MartialRanks.add("Peak Martial Grandmaster VII");
        Main.MartialRanks.add("Peak Martial Grandmaster VIII");
        Main.MartialRanks.add("Peak Martial Grandmaster IX");
        Main.MartialRanks.add("Peak Martial Grandmaster X");
        Main.MartialRanks.add("Lesser Martial Lord I");
        Main.MartialRanks.add("Lesser Martial Lord II");
        Main.MartialRanks.add("Lesser Martial Lord III");
        Main.MartialRanks.add("Lesser Martial Lord IV");
        Main.MartialRanks.add("Lesser Martial Lord V");
        Main.MartialRanks.add("Lesser Martial Lord VI");
        Main.MartialRanks.add("Lesser Martial Lord VII");
        Main.MartialRanks.add("Lesser Martial Lord VIII");
        Main.MartialRanks.add("Lesser Martial Lord IX");
        Main.MartialRanks.add("Lesser Martial Lord X");
        Main.MartialRanks.add("Martial Lord I");
        Main.MartialRanks.add("Martial Lord II");
        Main.MartialRanks.add("Martial Lord III");
        Main.MartialRanks.add("Martial Lord IV");
        Main.MartialRanks.add("Martial Lord V");
        Main.MartialRanks.add("Martial Lord VI");
        Main.MartialRanks.add("Martial Lord VII");
        Main.MartialRanks.add("Martial Lord VIII");
        Main.MartialRanks.add("Martial Lord IX");
        Main.MartialRanks.add("Martial Lord X");
        Main.MartialRanks.add("Greater Martial Lord I");
        Main.MartialRanks.add("Greater Martial Lord II");
        Main.MartialRanks.add("Greater Martial Lord III");
        Main.MartialRanks.add("Greater Martial Lord IV");
        Main.MartialRanks.add("Greater Martial Lord V");
        Main.MartialRanks.add("Greater Martial Lord VI");
        Main.MartialRanks.add("Greater Martial Lord VII");
        Main.MartialRanks.add("Greater Martial Lord VIII");
        Main.MartialRanks.add("Greater Martial Lord IX");
        Main.MartialRanks.add("Greater Martial Lord X");
        Main.MartialRanks.add("Peak Martial Lord I");
        Main.MartialRanks.add("Peak Martial Lord II");
        Main.MartialRanks.add("Peak Martial Lord III");
        Main.MartialRanks.add("Peak Martial Lord IV");
        Main.MartialRanks.add("Peak Martial Lord V");
        Main.MartialRanks.add("Peak Martial Lord VI");
        Main.MartialRanks.add("Peak Martial Lord VII");
        Main.MartialRanks.add("Peak Martial Lord VIII");
        Main.MartialRanks.add("Peak Martial Lord IX");
        Main.MartialRanks.add("Peak Martial Lord X");
        Main.MartialRanks.add("Lesser Martial King I");
        Main.MartialRanks.add("Lesser Martial King II");
        Main.MartialRanks.add("Lesser Martial King III");
        Main.MartialRanks.add("Lesser Martial King IV");
        Main.MartialRanks.add("Lesser Martial King V");
        Main.MartialRanks.add("Lesser Martial King VI");
        Main.MartialRanks.add("Lesser Martial King VII");
        Main.MartialRanks.add("Lesser Martial King VIII");
        Main.MartialRanks.add("Lesser Martial King IX");
        Main.MartialRanks.add("Lesser Martial King X");
        Main.MartialRanks.add("Martial King I");
        Main.MartialRanks.add("Martial King II");
        Main.MartialRanks.add("Martial King III");
        Main.MartialRanks.add("Martial King IV");
        Main.MartialRanks.add("Martial King V");
        Main.MartialRanks.add("Martial King VI");
        Main.MartialRanks.add("Martial King VII");
        Main.MartialRanks.add("Martial King VIII");
        Main.MartialRanks.add("Martial King IX");
        Main.MartialRanks.add("Martial King X");
        Main.MartialRanks.add("Greater Martial King I");
        Main.MartialRanks.add("Greater Martial King II");
        Main.MartialRanks.add("Greater Martial King III");
        Main.MartialRanks.add("Greater Martial King IV");
        Main.MartialRanks.add("Greater Martial King V");
        Main.MartialRanks.add("Greater Martial King VI");
        Main.MartialRanks.add("Greater Martial King VII");
        Main.MartialRanks.add("Greater Martial King VIII");
        Main.MartialRanks.add("Greater Martial King IX");
        Main.MartialRanks.add("Greater Martial King X");
        Main.MartialRanks.add("Peak Martial King I");
        Main.MartialRanks.add("Peak Martial King II");
        Main.MartialRanks.add("Peak Martial King III");
        Main.MartialRanks.add("Peak Martial King IV");
        Main.MartialRanks.add("Peak Martial King V");
        Main.MartialRanks.add("Peak Martial King VI");
        Main.MartialRanks.add("Peak Martial King VII");
        Main.MartialRanks.add("Peak Martial King VIII");
        Main.MartialRanks.add("Peak Martial King IX");
        Main.MartialRanks.add("Peak Martial King X");
        Main.MartialRanks.add("Lesser Martial Emperor I");
        Main.MartialRanks.add("Lesser Martial Emperor II");
        Main.MartialRanks.add("Lesser Martial Emperor III");
        Main.MartialRanks.add("Lesser Martial Emperor IV");
        Main.MartialRanks.add("Lesser Martial Emperor V");
        Main.MartialRanks.add("Lesser Martial Emperor VI");
        Main.MartialRanks.add("Lesser Martial Emperor VII");
        Main.MartialRanks.add("Lesser Martial Emperor VIII");
        Main.MartialRanks.add("Lesser Martial Emperor IX");
        Main.MartialRanks.add("Lesser Martial Emperor X");
        Main.MartialRanks.add("Martial Emperor I");
        Main.MartialRanks.add("Martial Emperor II");
        Main.MartialRanks.add("Martial Emperor III");
        Main.MartialRanks.add("Martial Emperor IV");
        Main.MartialRanks.add("Martial Emperor V");
        Main.MartialRanks.add("Martial Emperor VI");
        Main.MartialRanks.add("Martial Emperor VII");
        Main.MartialRanks.add("Martial Emperor VIII");
        Main.MartialRanks.add("Martial Emperor IX");
        Main.MartialRanks.add("Martial Emperor X");
        Main.MartialRanks.add("Greater Martial Emperor I");
        Main.MartialRanks.add("Greater Martial Emperor II");
        Main.MartialRanks.add("Greater Martial Emperor III");
        Main.MartialRanks.add("Greater Martial Emperor IV");
        Main.MartialRanks.add("Greater Martial Emperor V");
        Main.MartialRanks.add("Greater Martial Emperor VI");
        Main.MartialRanks.add("Greater Martial Emperor VII");
        Main.MartialRanks.add("Greater Martial Emperor VIII");
        Main.MartialRanks.add("Greater Martial Emperor IX");
        Main.MartialRanks.add("Greater Martial Emperor X");
        Main.MartialRanks.add("Peak Martial Emperor I");
        Main.MartialRanks.add("Peak Martial Emperor II");
        Main.MartialRanks.add("Peak Martial Emperor III");
        Main.MartialRanks.add("Peak Martial Emperor IV");
        Main.MartialRanks.add("Peak Martial Emperor V");
        Main.MartialRanks.add("Peak Martial Emperor VI");
        Main.MartialRanks.add("Peak Martial Emperor VII");
        Main.MartialRanks.add("Peak Martial Emperor VIII");
        Main.MartialRanks.add("Peak Martial Emperor IX");
        Main.MartialRanks.add("Peak Martial Emperor X");
        Main.MartialRanks.add("Lesser Martial Sovereign I");
        Main.MartialRanks.add("Lesser Martial Sovereign II");
        Main.MartialRanks.add("Lesser Martial Sovereign III");
        Main.MartialRanks.add("Lesser Martial Sovereign IV");
        Main.MartialRanks.add("Lesser Martial Sovereign V");
        Main.MartialRanks.add("Lesser Martial Sovereign VI");
        Main.MartialRanks.add("Lesser Martial Sovereign VII");
        Main.MartialRanks.add("Lesser Martial Sovereign VIII");
        Main.MartialRanks.add("Lesser Martial Sovereign IX");
        Main.MartialRanks.add("Lesser Martial Sovereign X");
        Main.MartialRanks.add("Martial Sovereign I");
        Main.MartialRanks.add("Martial Sovereign II");
        Main.MartialRanks.add("Martial Sovereign III");
        Main.MartialRanks.add("Martial Sovereign IV");
        Main.MartialRanks.add("Martial Sovereign V");
        Main.MartialRanks.add("Martial Sovereign VI");
        Main.MartialRanks.add("Martial Sovereign VII");
        Main.MartialRanks.add("Martial Sovereign VIII");
        Main.MartialRanks.add("Martial Sovereign IX");
        Main.MartialRanks.add("Martial Sovereign X");
        Main.MartialRanks.add("Greater Martial Sovereign I");
        Main.MartialRanks.add("Greater Martial Sovereign II");
        Main.MartialRanks.add("Greater Martial Sovereign III");
        Main.MartialRanks.add("Greater Martial Sovereign IV");
        Main.MartialRanks.add("Greater Martial Sovereign V");
        Main.MartialRanks.add("Greater Martial Sovereign VI");
        Main.MartialRanks.add("Greater Martial Sovereign VII");
        Main.MartialRanks.add("Greater Martial Sovereign VIII");
        Main.MartialRanks.add("Greater Martial Sovereign IX");
        Main.MartialRanks.add("Greater Martial Sovereign X");
        Main.MartialRanks.add("Peak Martial Sovereign I");
        Main.MartialRanks.add("Peak Martial Sovereign II");
        Main.MartialRanks.add("Peak Martial Sovereign III");
        Main.MartialRanks.add("Peak Martial Sovereign IV");
        Main.MartialRanks.add("Peak Martial Sovereign V");
        Main.MartialRanks.add("Peak Martial Sovereign VI");
        Main.MartialRanks.add("Peak Martial Sovereign VII");
        Main.MartialRanks.add("Peak Martial Sovereign VIII");
        Main.MartialRanks.add("Peak Martial Sovereign IX");
        Main.MartialRanks.add("Peak Martial Sovereign X");
        Main.MartialRanks.add("Lesser Martial Spirit I");
        Main.MartialRanks.add("Lesser Martial Spirit II");
        Main.MartialRanks.add("Lesser Martial Spirit III");
        Main.MartialRanks.add("Lesser Martial Spirit IV");
        Main.MartialRanks.add("Lesser Martial Spirit V");
        Main.MartialRanks.add("Lesser Martial Spirit VI");
        Main.MartialRanks.add("Lesser Martial Spirit VII");
        Main.MartialRanks.add("Lesser Martial Spirit VIII");
        Main.MartialRanks.add("Lesser Martial Spirit IX");
        Main.MartialRanks.add("Lesser Martial Spirit X");
        Main.MartialRanks.add("Martial Spirit I");
        Main.MartialRanks.add("Martial Spirit II");
        Main.MartialRanks.add("Martial Spirit III");
        Main.MartialRanks.add("Martial Spirit IV");
        Main.MartialRanks.add("Martial Spirit V");
        Main.MartialRanks.add("Martial Spirit VI");
        Main.MartialRanks.add("Martial Spirit VII");
        Main.MartialRanks.add("Martial Spirit VIII");
        Main.MartialRanks.add("Martial Spirit IX");
        Main.MartialRanks.add("Martial Spirit X");
        Main.MartialRanks.add("Greater Martial Spirit I");
        Main.MartialRanks.add("Greater Martial Spirit II");
        Main.MartialRanks.add("Greater Martial Spirit III");
        Main.MartialRanks.add("Greater Martial Spirit IV");
        Main.MartialRanks.add("Greater Martial Spirit V");
        Main.MartialRanks.add("Greater Martial Spirit VI");
        Main.MartialRanks.add("Greater Martial Spirit VII");
        Main.MartialRanks.add("Greater Martial Spirit VIII");
        Main.MartialRanks.add("Greater Martial Spirit IX");
        Main.MartialRanks.add("Greater Martial Spirit X");
        Main.MartialRanks.add("Peak Martial Spirit I");
        Main.MartialRanks.add("Peak Martial Spirit II");
        Main.MartialRanks.add("Peak Martial Spirit III");
        Main.MartialRanks.add("Peak Martial Spirit IV");
        Main.MartialRanks.add("Peak Martial Spirit V");
        Main.MartialRanks.add("Peak Martial Spirit VI");
        Main.MartialRanks.add("Peak Martial Spirit VII");
        Main.MartialRanks.add("Peak Martial Spirit VIII");
        Main.MartialRanks.add("Peak Martial Spirit IX");
        Main.MartialRanks.add("Peak Martial Spirit X");
        Main.MartialRanks.add("Lesser Martial Ancestor I");
        Main.MartialRanks.add("Lesser Martial Ancestor II");
        Main.MartialRanks.add("Lesser Martial Ancestor III");
        Main.MartialRanks.add("Lesser Martial Ancestor IV");
        Main.MartialRanks.add("Lesser Martial Ancestor V");
        Main.MartialRanks.add("Lesser Martial Ancestor VI");
        Main.MartialRanks.add("Lesser Martial Ancestor VII");
        Main.MartialRanks.add("Lesser Martial Ancestor VIII");
        Main.MartialRanks.add("Lesser Martial Ancestor IX");
        Main.MartialRanks.add("Lesser Martial Ancestor X");
        Main.MartialRanks.add("Martial Ancestor I");
        Main.MartialRanks.add("Martial Ancestor II");
        Main.MartialRanks.add("Martial Ancestor III");
        Main.MartialRanks.add("Martial Ancestor IV");
        Main.MartialRanks.add("Martial Ancestor V");
        Main.MartialRanks.add("Martial Ancestor VI");
        Main.MartialRanks.add("Martial Ancestor VII");
        Main.MartialRanks.add("Martial Ancestor VIII");
        Main.MartialRanks.add("Martial Ancestor IX");
        Main.MartialRanks.add("Martial Ancestor X");
        Main.MartialRanks.add("Greater Martial Ancestor I");
        Main.MartialRanks.add("Greater Martial Ancestor II");
        Main.MartialRanks.add("Greater Martial Ancestor III");
        Main.MartialRanks.add("Greater Martial Ancestor IV");
        Main.MartialRanks.add("Greater Martial Ancestor V");
        Main.MartialRanks.add("Greater Martial Ancestor VI");
        Main.MartialRanks.add("Greater Martial Ancestor VII");
        Main.MartialRanks.add("Greater Martial Ancestor VIII");
        Main.MartialRanks.add("Greater Martial Ancestor IX");
        Main.MartialRanks.add("Greater Martial Ancestor X");
        Main.MartialRanks.add("Peak Martial Ancestor I");
        Main.MartialRanks.add("Peak Martial Ancestor II");
        Main.MartialRanks.add("Peak Martial Ancestor III");
        Main.MartialRanks.add("Peak Martial Ancestor IV");
        Main.MartialRanks.add("Peak Martial Ancestor V");
        Main.MartialRanks.add("Peak Martial Ancestor VI");
        Main.MartialRanks.add("Peak Martial Ancestor VII");
        Main.MartialRanks.add("Peak Martial Ancestor VIII");
        Main.MartialRanks.add("Peak Martial Ancestor IX");
        Main.MartialRanks.add("Peak Martial Ancestor X");
        Main.MartialRanks.add("Lesser Martial Saint I");
        Main.MartialRanks.add("Lesser Martial Saint II");
        Main.MartialRanks.add("Lesser Martial Saint III");
        Main.MartialRanks.add("Lesser Martial Saint IV");
        Main.MartialRanks.add("Lesser Martial Saint V");
        Main.MartialRanks.add("Lesser Martial Saint VI");
        Main.MartialRanks.add("Lesser Martial Saint VII");
        Main.MartialRanks.add("Lesser Martial Saint VIII");
        Main.MartialRanks.add("Lesser Martial Saint IX");
        Main.MartialRanks.add("Lesser Martial Saint X");
        Main.MartialRanks.add("Martial Saint I");
        Main.MartialRanks.add("Martial Saint II");
        Main.MartialRanks.add("Martial Saint III");
        Main.MartialRanks.add("Martial Saint IV");
        Main.MartialRanks.add("Martial Saint V");
        Main.MartialRanks.add("Martial Saint VI");
        Main.MartialRanks.add("Martial Saint VII");
        Main.MartialRanks.add("Martial Saint VIII");
        Main.MartialRanks.add("Martial Saint IX");
        Main.MartialRanks.add("Martial Saint X");
        Main.MartialRanks.add("Greater Martial Saint I");
        Main.MartialRanks.add("Greater Martial Saint II");
        Main.MartialRanks.add("Greater Martial Saint III");
        Main.MartialRanks.add("Greater Martial Saint IV");
        Main.MartialRanks.add("Greater Martial Saint V");
        Main.MartialRanks.add("Greater Martial Saint VI");
        Main.MartialRanks.add("Greater Martial Saint VII");
        Main.MartialRanks.add("Greater Martial Saint VIII");
        Main.MartialRanks.add("Greater Martial Saint IX");
        Main.MartialRanks.add("Greater Martial Saint X");
        Main.MartialRanks.add("Peak Martial Saint I");
        Main.MartialRanks.add("Peak Martial Saint II");
        Main.MartialRanks.add("Peak Martial Saint III");
        Main.MartialRanks.add("Peak Martial Saint IV");
        Main.MartialRanks.add("Peak Martial Saint V");
        Main.MartialRanks.add("Peak Martial Saint VI");
        Main.MartialRanks.add("Peak Martial Saint VII");
        Main.MartialRanks.add("Peak Martial Saint VIII");
        Main.MartialRanks.add("Peak Martial Saint IX");
        Main.MartialRanks.add("Peak Martial Saint X");
    }
}
